data = [{'ticker': 'NVDA', 'name': 'NVIDIA Corporation'},
 {'ticker': 'MSFT', 'name': 'Microsoft Corporation'},
 {'ticker': 'AAPL', 'name': 'Apple Inc.'},
 {'ticker': 'GOOG', 'name': 'Alphabet Inc.'},
 {'ticker': 'AMZN', 'name': 'Amazon.com, Inc.'},
 {'ticker': 'META', 'name': 'Meta Platforms, Inc.'},
 {'ticker': 'AVGO', 'name': 'Broadcom Inc.'},
 {'ticker': 'TSLA', 'name': 'Tesla, Inc.'},
 {'ticker': 'BRK-B', 'name': 'Berkshire Hathaway Inc.'},
 {'ticker': 'ORCL', 'name': 'Oracle Corporation'},
 {'ticker': 'WMT', 'name': 'Walmart Inc.'},
 {'ticker': 'JPM', 'name': 'JPMorgan Chase & Co.'},
 {'ticker': 'LLY', 'name': 'Eli Lilly and Company'},
 {'ticker': 'V', 'name': 'Visa Inc.'},
 {'ticker': 'NFLX', 'name': 'Netflix, Inc.'},
 {'ticker': 'MA', 'name': 'Mastercard Incorporated'},
 {'ticker': 'XOM', 'name': 'Exxon Mobil Corporation'},
 {'ticker': 'JNJ', 'name': 'Johnson & Johnson'},
 {'ticker': 'COST', 'name': 'Costco Wholesale Corporation'},
 {'ticker': 'PLTR', 'name': 'Palantir Technologies, Inc.'},
 {'ticker': 'ABBV', 'name': 'AbbVie Inc.'},
 {'ticker': 'HD', 'name': 'The Home Depot, Inc.'},
 {'ticker': 'BAC', 'name': 'Bank of America Corporation'},
 {'ticker': 'AMD', 'name': 'Advanced Micro Devices, Inc.'},
 {'ticker': 'PG', 'name': 'Procter & Gamble Company'},
 {'ticker': 'UNH', 'name': 'UnitedHealth Group Incorporated'},
 {'ticker': 'GE', 'name': 'General Electric Company'},
 {'ticker': 'CVX', 'name': 'Chevron Corporation'},
 {'ticker': 'KO', 'name': 'The Coca-Cola Company'},
 {'ticker': 'CSCO', 'name': 'Cisco Systems, Inc.'},
 {'ticker': 'WFC', 'name': 'Wells Fargo & Company'},
 {'ticker': 'TMUS', 'name': 'T-Mobile US, Inc.'},
 {'ticker': 'IBM', 'name': 'International Business Machines Corporation'},
 {'ticker': 'PM', 'name': 'Philip Morris International Inc.'},
 {'ticker': 'MS', 'name': 'Morgan Stanley'},
 {'ticker': 'CAT', 'name': 'Caterpillar Inc.'},
 {'ticker': 'CRM', 'name': 'Salesforce, Inc.'},
 {'ticker': 'ABT', 'name': 'Abbott Laboratories'},
 {'ticker': 'GS', 'name': 'The Goldman Sachs Group, Inc.'},
 {'ticker': 'AXP', 'name': 'American Express Company'},
 {'ticker': 'MCD', 'name': "McDonald's Corporation"},
 {'ticker': 'MRK', 'name': 'Merck & Co., Inc.'},
 {'ticker': 'RTX', 'name': 'Raytheon Technologies Corporation'},
 {'ticker': 'MU', 'name': 'Micron Technology, Inc.'},
 {'ticker': 'PEP', 'name': 'PepsiCo, Inc.'},
 {'ticker': 'TMO', 'name': 'Thermo Fisher Scientific Inc.'},
 {'ticker': 'DIS', 'name': 'Walt Disney Company'},
 {'ticker': 'BX', 'name': 'Blackstone Inc.'},
 {'ticker': 'UBER', 'name': 'Uber Technologies, Inc.'},
 {'ticker': 'APP', 'name': 'AppLovin Corporation'},
 {'ticker': 'NOW', 'name': 'ServiceNow, Inc.'},
 {'ticker': 'T', 'name': 'AT&T Inc.'},
 {'ticker': 'BLK', 'name': 'BlackRock, Inc.'},
 {'ticker': 'INTU', 'name': 'Intuit Inc.'},
 {'ticker': 'C', 'name': 'Citigroup Inc.'},
 {'ticker': 'ANET', 'name': 'Arista Networks, Inc.'},
 {'ticker': 'NEE', 'name': 'NextEra Energy, Inc.'},
 {'ticker': 'QCOM', 'name': 'QUALCOMM Incorporated'},
 {'ticker': 'AMAT', 'name': 'Applied Materials, Inc.'},
 {'ticker': 'LRCX', 'name': 'Lam Research Corporation'},
 {'ticker': 'SCHW', 'name': 'Charles Schwab Corporation'},
 {'ticker': 'GEV', 'name': 'GE Vernova'},
 {'ticker': 'BKNG', 'name': 'Booking Holdings Inc.'},
 {'ticker': 'VZ', 'name': 'Verizon Communications Inc.'},
 {'ticker': 'INTC', 'name': 'Intel Corporation'},
 {'ticker': 'BA', 'name': 'The Boeing Company'},
 {'ticker': 'TJX', 'name': 'The TJX Companies, Inc.'},
 {'ticker': 'AMGN', 'name': 'Amgen Inc.'},
 {'ticker': 'TXN', 'name': 'Texas Instruments Incorporated'},
 {'ticker': 'ISRG', 'name': 'Intuitive Surgical, Inc.'},
 {'ticker': 'APH', 'name': 'Amphenol Corporation'},
 {'ticker': 'SPGI', 'name': 'S&P Global Inc.'},
 {'ticker': 'DHR', 'name': 'Danaher Corporation'},
 {'ticker': 'GILD', 'name': 'Gilead Sciences, Inc.'},
 {'ticker': 'BSX', 'name': 'Boston Scientific Corporation'},
 {'ticker': 'PANW', 'name': 'Palo Alto Networks, Inc.'},
 {'ticker': 'SYK', 'name': 'Stryker Corporation'},
 {'ticker': 'PFE', 'name': 'Pfizer Inc.'},
 {'ticker': 'ADBE', 'name': 'Adobe Inc.'},
 {'ticker': 'PGR', 'name': 'The Progressive Corporation'},
 {'ticker': 'UNP', 'name': 'Union Pacific Corporation'},
 {'ticker': 'KLAC', 'name': 'KLA Corporation'},
 {'ticker': 'COF', 'name': 'Capital One Financial Corporation'},
 {'ticker': 'LOW', 'name': "Lowe's Companies, Inc."},
 {'ticker': 'HON', 'name': 'Honeywell International Inc.'},
 {'ticker': 'CRWD', 'name': 'CrowdStrike Holdings, Inc.'},
 {'ticker': 'HOOD', 'name': 'Robinhood Markets, Inc.'},
 {'ticker': 'DE', 'name': 'Deere & Company'},
 {'ticker': 'LMT', 'name': 'Lockheed Martin Corporation'},
 {'ticker': 'IBKR', 'name': 'Interactive Brokers Group, Inc.'},
 {'ticker': 'ADP', 'name': 'Automatic Data Processing, Inc.'},
 {'ticker': 'CEG', 'name': 'Constellation Energy Corporation'},
 {'ticker': 'DASH', 'name': 'DoorDash, Inc.'},
 {'ticker': 'ADI', 'name': 'Analog Devices, Inc.'},
 {'ticker': 'KKR', 'name': 'KKR & Co. Inc.'},
 {'ticker': 'WELL', 'name': 'Welltower Inc.'},
 {'ticker': 'COP', 'name': 'ConocoPhillips'},
 {'ticker': 'MO', 'name': 'Altria Group, Inc.'},
 {'ticker': 'CMCSA', 'name': 'Comcast Corporation'},
 {'ticker': 'SO', 'name': 'Southern Company'},
 {'ticker': 'VRTX', 'name': 'Vertex Pharmaceuticals Incorporated'},
 {'ticker': 'PLD', 'name': 'Prologis, Inc.'},
 {'ticker': 'SCCO', 'name': 'Southern Copper Corporation'},
 {'ticker': 'DELL', 'name': 'Dell Technologies Inc.'},
 {'ticker': 'MMC', 'name': 'Marsh & McLennan Companies, Inc.'},
 {'ticker': 'CVS', 'name': 'CVS Health Corporation'},
 {'ticker': 'CME', 'name': 'CME Group Inc.'},
 {'ticker': 'DUK', 'name': 'Duke Energy Corporation'},
 {'ticker': 'NKE', 'name': 'NIKE, Inc.'},
 {'ticker': 'NEM', 'name': 'Newmont Corporation'},
 {'ticker': 'HCA', 'name': 'HCA Healthcare, Inc.'},
 {'ticker': 'MCK', 'name': 'McKesson Corporation'},
 {'ticker': 'ICE', 'name': 'Intercontinental Exchange, Inc.'},
 {'ticker': 'PH', 'name': 'Parker-Hannifin Corporation'},
 {'ticker': 'SBUX', 'name': 'Starbucks Corporation'},
 {'ticker': 'GD', 'name': 'General Dynamics Corporation'},
 {'ticker': 'NOC', 'name': 'Northrop Grumman Corporation'},
 {'ticker': 'RBLX', 'name': 'Roblox Corporation'},
 {'ticker': 'BMY', 'name': 'Bristol-Myers Squibb Company'},
 {'ticker': 'ORLY', 'name': "O'Reilly Automotive, Inc."},
 {'ticker': 'COIN', 'name': 'Coinbase Global, Inc.'},
 {'ticker': 'WM', 'name': 'Waste Management, Inc.'},
 {'ticker': 'CDNS', 'name': 'Cadence Design Systems, Inc.'},
 {'ticker': 'MSTR', 'name': 'MicroStrategy Incorporated'},
 {'ticker': 'AMT', 'name': 'American Tower Corporation'},
 {'ticker': 'MCO', 'name': "Moody's Corporation"},
 {'ticker': 'SNOW', 'name': 'Snowflake Inc.'},
 {'ticker': 'SHW', 'name': 'Sherwin-Williams Company'},
 {'ticker': 'RCL', 'name': 'Royal Caribbean Group'},
 {'ticker': 'SNPS', 'name': 'Synopsys, Inc.'},
 {'ticker': 'MMM', 'name': '3M Company'},
 {'ticker': 'CI', 'name': 'Cigna Group'},
 {'ticker': 'MDLZ', 'name': 'Mondelez International, Inc.'},
 {'ticker': 'EQIX', 'name': 'Equinix, Inc.'},
 {'ticker': 'ELV', 'name': 'Elevance Health, Inc.'},
 {'ticker': 'MSI', 'name': 'Motorola Solutions, Inc.'},
 {'ticker': 'ECL', 'name': 'Ecolab Inc.'},
 {'ticker': 'AJG', 'name': 'Arthur J. Gallagher & Co.'},
 {'ticker': 'HWM', 'name': 'Howmet Aerospace Inc.'},
 {'ticker': 'WMB', 'name': 'The Williams Companies, Inc.'},
 {'ticker': 'NET', 'name': 'Cloudflare, Inc.'},
 {'ticker': 'CTAS', 'name': 'Cintas Corporation'},
 {'ticker': 'MRVL', 'name': 'Marvell Technology, Inc.'},
 {'ticker': 'BK', 'name': 'The Bank of New York Mellon Corporation'},
 {'ticker': 'PNC', 'name': 'PNC Financial Services Group, Inc.'},
 {'ticker': 'TDG', 'name': 'TransDigm Group Incorporated'},
 {'ticker': 'GLW', 'name': 'Corning Inc.'},
 {'ticker': 'ABNB', 'name': 'Airbnb, Inc.'},
 {'ticker': 'USB', 'name': 'U.S. Bancorp'},
 {'ticker': 'EMR', 'name': 'Emerson Electric Co.'},
 {'ticker': 'MAR', 'name': 'Marriott International, Inc.'},
 {'ticker': 'ITW', 'name': 'Illinois Tool Works Inc.'},
 {'ticker': 'UPS', 'name': 'United Parcel Service, Inc.'},
 {'ticker': 'RSG', 'name': 'Republic Services, Inc.'},
 {'ticker': 'VST', 'name': 'Vistra Corp.'},
 {'ticker': 'APO', 'name': 'Apollo Global Management, Inc.'},
 {'ticker': 'AZO', 'name': 'AutoZone, Inc.'},
 {'ticker': 'CRWV', 'name': 'CoreWeave, Inc.'},
 {'ticker': 'EPD', 'name': 'Enterprise Products Partners L.P.'},
 {'ticker': 'SPG', 'name': 'Simon Property Group, Inc.'},
 {'ticker': 'FI', 'name': 'Fiserv, Inc.'},
 {'ticker': 'CSX', 'name': 'CSX Corporation'},
 {'ticker': 'VRT', 'name': 'Vertiv Holdings Co.'},
 {'ticker': 'MNST', 'name': 'Monster Beverage Corporation'},
 {'ticker': 'ADSK', 'name': 'Autodesk, Inc.'},
 {'ticker': 'NSC', 'name': 'Norfolk Southern Corporation'},
 {'ticker': 'PYPL', 'name': 'PayPal Holdings, Inc.'},
 {'ticker': 'FTNT', 'name': 'Fortinet, Inc.'},
 {'ticker': 'PWR', 'name': 'Quanta Services, Inc.'},
 {'ticker': 'AEP', 'name': 'American Electric Power Company, Inc.'},
 {'ticker': 'O', 'name': 'Realty Income Corporation'},
 {'ticker': 'BDX', 'name': 'Becton, Dickinson and Company'},
 {'ticker': 'GM', 'name': 'General Motors Company'},
 {'ticker': 'PSA', 'name': 'Public Storage'},
 {'ticker': 'PSX', 'name': 'Phillips 66'},
 {'ticker': 'D', 'name': 'Dominion Energy, Inc.'},
 {'ticker': 'NDAQ', 'name': 'Nasdaq, Inc.'},
 {'ticker': 'IDXX', 'name': 'IDEXX Laboratories, Inc.'},
 {'ticker': 'ROST', 'name': 'Ross Stores, Inc.'},
 {'ticker': 'VLO', 'name': 'Valero Energy Corporation'},
 {'ticker': 'EA', 'name': 'Electronic Arts Inc.'},
 {'ticker': 'LNG', 'name': 'Cheniere Energy, Inc.'},
 {'ticker': 'ZS', 'name': 'Zscaler, Inc.'},
 {'ticker': 'MPLX', 'name': 'MPLX LP'},
 {'ticker': 'PCAR', 'name': 'PACCAR Inc.'},
 {'ticker': 'FAST', 'name': 'Fastenal Company'},
 {'ticker': 'CARR', 'name': 'Carrier Global Corporation'},
 {'ticker': 'SLB', 'name': 'SLB'},
 {'ticker': 'XEL', 'name': 'Xcel Energy Inc.'},
 {'ticker': 'TTWO', 'name': 'Take-Two Interactive Software, Inc.'},
 {'ticker': 'EXC', 'name': 'Exelon Corporation'},
 {'ticker': 'MPWR', 'name': 'Monolithic Power Systems, Inc.'},
 {'ticker': 'ARES', 'name': 'Ares Management Corporation'},
 {'ticker': 'VEEV', 'name': 'Veeva Systems Inc.'},
 {'ticker': 'F', 'name': 'Ford Motor Company'},
 {'ticker': 'PAYX', 'name': 'Paychex, Inc.'},
 {'ticker': 'SQ', 'name': 'Block, Inc.'},
 {'ticker': 'CBRE', 'name': 'CBRE Group, Inc.'},
 {'ticker': 'DHI', 'name': 'D.R. Horton, Inc.'},
 {'ticker': 'AMP', 'name': 'Ameriprise Financial, Inc.'},
 {'ticker': 'AIG', 'name': 'American International Group, Inc.'},
 {'ticker': 'BKR', 'name': 'Baker Hughes Company'},
 {'ticker': 'GWW', 'name': 'W.W. Grainger, Inc.'},
 {'ticker': 'KR', 'name': 'Kroger Co.'},
 {'ticker': 'WCN', 'name': 'Waste Connections, Inc.'},
 {'ticker': 'WBD', 'name': 'Warner Bros. Discovery, Inc.'},
 {'ticker': 'OKE', 'name': 'ONEOK, Inc.'},
 {'ticker': 'EW', 'name': 'Edwards Lifesciences Corporation'},
 {'ticker': 'ETR', 'name': 'Entergy Corporation'},
 {'ticker': 'CPRT', 'name': 'Copart, Inc.'},
 {'ticker': 'CTVA', 'name': 'Corteva, Inc.'},
 {'ticker': 'MSCI', 'name': 'MSCI Inc.'},
 {'ticker': 'AME', 'name': 'AMETEK, Inc.'},
 {'ticker': 'CCI', 'name': 'Crown Castle International Corp.'},
 {'ticker': 'OXY', 'name': 'Occidental Petroleum Corporation'},
 {'ticker': 'SYM', 'name': 'Symbotic, Inc.'},
 {'ticker': 'UI', 'name': 'Ubiquiti Inc.'},
 {'ticker': 'FANG', 'name': 'Diamondback Energy, Inc.'},
 {'ticker': 'EBAY', 'name': 'eBay Inc.'},
 {'ticker': 'PEG', 'name': 'Public Service Enterprise Group Inc.'},
 {'ticker': 'WDC', 'name': 'Western Digital Corporation'},
 {'ticker': 'VMC', 'name': 'Vulcan Materials Company'},
 {'ticker': 'RMD', 'name': 'ResMed Inc.'},
 {'ticker': 'TGT', 'name': 'Target Corporation'},
 {'ticker': 'FICO', 'name': 'Fair Isaac Corporation'},
 {'ticker': 'KMB', 'name': 'Kimberly-Clark Corporation'},
 {'ticker': 'CVNA', 'name': 'Carvana Co.'},
 {'ticker': 'A', 'name': 'Agilent Technologies, Inc.'},
 {'ticker': 'YUM', 'name': 'Yum! Brands, Inc.'}]
